export const permissionsOptions = [
  { label: "Create Ticket", value: "Create Ticket" },
  { label: "Delete Ticket", value: "Delete Ticket" },
  { label: "Edit Ticket", value: "Edit Ticket" },
  { label: "Read Ticket", value: "Read Ticket" },
  { label: "Create Provider", value: "Create Provider" },
  { label: "Delete Provider", value: "Delete Provider" },
  { label: "Edit Provider", value: "Edit Provider" },
  { label: "Read Provider", value: "Read Provider" },
  { label: "Create Agent", value: "Create Agent" },
  { label: "Delete Agent", value: "Delete Agent" },
  { label: "Edit Agent", value: "Edit Agent" },
  { label: "Read Agent", value: "Read Agent" },
  { label: "Create User", value: "Create User" },
  { label: "Delete User", value: "Delete User" },
  { label: "Edit User", value: "Edit User" },
  { label: "Read User", value: "Read User" },
  { label: "Create Ledger", value: "Create Ledger" },
  { label: "Delete Ledger", value: "Delete Ledger" },
  { label: "Edit Ledger", value: "Edit Ledger" },
  { label: "Read Ledger", value: "Read Ledger" },
  { label: "Create Payment", value: "Create Payment" },
  { label: "Delete Payment", value: "Delete Payment" },
  { label: "Edit Payment", value: "Edit Payment" },
  { label: "Read Payment", value: "Read Payment" },
  { label: "Create Payment Method", value: "Create Payment Method" },
  { label: "Delete Payment Method", value: "Delete Payment Method" },
  { label: "Edit Payment Method", value: "Edit Payment Method" },
  { label: "Read Payment Method", value: "Read Payment Method" },
];
